# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f38762cf9c2d091e116626055e0faa6175af1cb9f0dd88656e5303cc93054d22ce3abc8855283ed2470584e7ba7a8c11dc77449819a820889d3d5fbdb4cd618

test:
  secret_key_base: c2f9ffca1613bf2087107fb4b57f187883dbc4c4f5f434305f54e5b7c6bbe4b69b795fb86d6b801f2b5b30ef650ad40e2e1b72f60c7f7e8b05142e014f166e7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
